/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Rizki Ananda
 */
public class menu extends javax.swing.JFrame {
    JasperReport JasperReport;
    JasperDesign JasperDesign;
    JasperPrint JasperPrint;
    Map<String, Object> param = new HashMap<>();
    public void tanggal(){
        Date tgl = new Date();
        SimpleDateFormat a = new SimpleDateFormat("dd-MM-yyyy");
        tanggal.setText(a.format(tgl));
    }
    private void waktu(){
        new Thread(){
        int jamskrg;
    public void run(){
        while (jamskrg == 0){
            Calendar kal = new GregorianCalendar();
            int jam = kal.get(Calendar.HOUR);
            int menit = kal.get(Calendar.MINUTE);
            int detik = kal.get(Calendar.SECOND);
            int am_pm = kal.get(Calendar.AM_PM);
            String siang_malam = "";
            if (am_pm==1){
                siang_malam = "PM";
            }else{
                siang_malam = "AM";
            }
            String time = jam+":"+menit+":"+detik;
            String day = siang_malam;
            waktu.setText(time);
            ampm.setText(day);
        }
        }
    }.start();
}
    /**
     * Creates new form Menu
     */
    public menu() {
        initComponents();
        setLocationRelativeTo(null);
        tanggal();
        waktu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        logo1 = new background.logo();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnkaryawan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnclient = new javax.swing.JButton();
        btnevent = new javax.swing.JButton();
        btnkonsumsi = new javax.swing.JButton();
        btnperlengkapan = new javax.swing.JButton();
        btn_pembayaran = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btn_pengeluaran = new javax.swing.JButton();
        btnRepotClient = new javax.swing.JButton();
        btnReportEvent = new javax.swing.JButton();
        btnReportPerlengkapan = new javax.swing.JButton();
        btnReportPembayaran = new javax.swing.JButton();
        btnReportPengeluaran = new javax.swing.JButton();
        blogout = new javax.swing.JButton();
        tanggal = new javax.swing.JLabel();
        waktu = new javax.swing.JLabel();
        ampm = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CV. ANGGALA ESTU PRATAMA");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CV. ANGGALA ESTU PRATAMA");

        logo1.setBackground(new java.awt.Color(0, 51, 153));

        javax.swing.GroupLayout logo1Layout = new javax.swing.GroupLayout(logo1);
        logo1.setLayout(logo1Layout);
        logo1Layout.setHorizontalGroup(
            logo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        logo1Layout.setVerticalGroup(
            logo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1193, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(243, 243, 243)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
                    .addGap(243, 243, 243)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(jLabel3)
                    .addContainerGap(29, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnkaryawan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnkaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/karyawan.png"))); // NOI18N
        btnkaryawan.setText("Data Karyawan");
        btnkaryawan.setBorder(null);
        btnkaryawan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnkaryawan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnkaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkaryawanActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/master.png"))); // NOI18N
        jLabel2.setText("DATA MASTER");

        btnclient.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/client.png"))); // NOI18N
        btnclient.setText("Data Client");
        btnclient.setBorder(null);
        btnclient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnclient.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclientActionPerformed(evt);
            }
        });

        btnevent.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnevent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/event.png"))); // NOI18N
        btnevent.setText("Data Event");
        btnevent.setBorder(null);
        btnevent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnevent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnevent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneventActionPerformed(evt);
            }
        });

        btnkonsumsi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnkonsumsi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/catering.png"))); // NOI18N
        btnkonsumsi.setText("Data Konsumsi");
        btnkonsumsi.setBorder(null);
        btnkonsumsi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnkonsumsi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnkonsumsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkonsumsiActionPerformed(evt);
            }
        });

        btnperlengkapan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnperlengkapan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/barang.png"))); // NOI18N
        btnperlengkapan.setText("Data Perlengkapan");
        btnperlengkapan.setBorder(null);
        btnperlengkapan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnperlengkapan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnperlengkapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnperlengkapanActionPerformed(evt);
            }
        });

        btn_pembayaran.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_pembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/bayar.png"))); // NOI18N
        btn_pembayaran.setText("Pembayaran");
        btn_pembayaran.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pembayaranActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/transaksi.png"))); // NOI18N
        jLabel4.setText("TRANSAKSI");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/report.png"))); // NOI18N
        jLabel5.setText("LAPORAN");

        btn_pengeluaran.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_pengeluaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/selling.png"))); // NOI18N
        btn_pengeluaran.setText("Pengeluaran");
        btn_pengeluaran.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_pengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pengeluaranActionPerformed(evt);
            }
        });

        btnRepotClient.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnRepotClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/reportclient.png"))); // NOI18N
        btnRepotClient.setText("Client");
        btnRepotClient.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRepotClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepotClientActionPerformed(evt);
            }
        });

        btnReportEvent.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnReportEvent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/reportevent.png"))); // NOI18N
        btnReportEvent.setText("Event");
        btnReportEvent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReportEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportEventActionPerformed(evt);
            }
        });

        btnReportPerlengkapan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnReportPerlengkapan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/logistik.png"))); // NOI18N
        btnReportPerlengkapan.setText("Perlengkapan");
        btnReportPerlengkapan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReportPerlengkapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportPerlengkapanActionPerformed(evt);
            }
        });

        btnReportPembayaran.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnReportPembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/bayar.png"))); // NOI18N
        btnReportPembayaran.setText("Pembayaran");
        btnReportPembayaran.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReportPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportPembayaranActionPerformed(evt);
            }
        });

        btnReportPengeluaran.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnReportPengeluaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/selling.png"))); // NOI18N
        btnReportPengeluaran.setText("Pengeluaran");
        btnReportPengeluaran.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReportPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportPengeluaranActionPerformed(evt);
            }
        });

        blogout.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        blogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/logout.png"))); // NOI18N
        blogout.setText("Logout");
        blogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        blogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blogoutActionPerformed(evt);
            }
        });

        tanggal.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        waktu.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        ampm.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btn_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btn_pengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnRepotClient, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnReportEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnReportPerlengkapan, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnReportPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnReportPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(blogout, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(btnperlengkapan, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnkonsumsi, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(btnkaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnclient, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnevent, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(784, 784, 784)
                        .addComponent(waktu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ampm, javax.swing.GroupLayout.DEFAULT_SIZE, 5, Short.MAX_VALUE)
                        .addGap(9, 9, 9))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_pengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRepotClient, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReportEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReportPerlengkapan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReportPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReportPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(waktu, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ampm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tanggal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnkaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnclient, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnevent, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnkonsumsi, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnperlengkapan, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(blogout, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(642, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 104, Short.MAX_VALUE)
                    .addComponent(jDesktopPane1)))
        );

        setSize(new java.awt.Dimension(1315, 798));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnkaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkaryawanActionPerformed
        // TODO add your handling code here:
        new DKaryawan().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnkaryawanActionPerformed

    private void blogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blogoutActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_blogoutActionPerformed

    private void btn_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pembayaranActionPerformed
        // TODO add your handling code here:
    new Pembayaran().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_pembayaranActionPerformed

    private void btn_pengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pengeluaranActionPerformed
        // TODO add your handling code here:
        new Pengeluaran().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_pengeluaranActionPerformed

    private void btnclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclientActionPerformed
        // TODO add your handling code here:
        new DataClient().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnclientActionPerformed

    private void btneventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneventActionPerformed
        // TODO add your handling code here:
        new DataEvent().setVisible(true);
        dispose();
    }//GEN-LAST:event_btneventActionPerformed

    private void btnperlengkapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnperlengkapanActionPerformed
        // TODO add your handling code here:
        new DataPerlengkapan().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnperlengkapanActionPerformed

    private void btnkonsumsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkonsumsiActionPerformed
        // TODO add your handling code here:
        new DataKonsumsi().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnkonsumsiActionPerformed

    private void btnRepotClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepotClientActionPerformed
        // TODO add your handling code here:
       ReportClient RC = new ReportClient();
       jDesktopPane1.add(RC);
       RC.setVisible(true);
    }//GEN-LAST:event_btnRepotClientActionPerformed

    private void btnReportEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportEventActionPerformed
        // TODO add your handling code here:
       ReportEvent RE = new ReportEvent();
       jDesktopPane1.add(RE);
       RE.setVisible(true);
    }//GEN-LAST:event_btnReportEventActionPerformed

    private void btnReportPerlengkapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportPerlengkapanActionPerformed
        // TODO add your handling code here:
       ReportPerlengkapan RP = new ReportPerlengkapan();
       jDesktopPane1.add(RP);
       RP.setVisible(true);
    }//GEN-LAST:event_btnReportPerlengkapanActionPerformed

    private void btnReportPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportPembayaranActionPerformed
        // TODO add your handling code here:
       ReportPembayaran RP = new ReportPembayaran();
       jDesktopPane1.add(RP);
       RP.setVisible(true);
    }//GEN-LAST:event_btnReportPembayaranActionPerformed

    private void btnReportPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportPengeluaranActionPerformed
        // TODO add your handling code here:
       ReportPengeluaran RP = new ReportPengeluaran();
       jDesktopPane1.add(RP);
       RP.setVisible(true);
    }//GEN-LAST:event_btnReportPengeluaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ampm;
    private javax.swing.JButton blogout;
    private javax.swing.JButton btnReportEvent;
    private javax.swing.JButton btnReportPembayaran;
    private javax.swing.JButton btnReportPengeluaran;
    private javax.swing.JButton btnReportPerlengkapan;
    private javax.swing.JButton btnRepotClient;
    private javax.swing.JButton btn_pembayaran;
    private javax.swing.JButton btn_pengeluaran;
    private javax.swing.JButton btnclient;
    private javax.swing.JButton btnevent;
    private javax.swing.JButton btnkaryawan;
    private javax.swing.JButton btnkonsumsi;
    private javax.swing.JButton btnperlengkapan;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private background.logo logo1;
    private javax.swing.JLabel tanggal;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables
}
